### ISSUE TITLE
[GENERAL]:  I can't figure out how to craft a quill

### ISSUE THREAD

**Issue by bakaemon** [HunterGhost27/Scribe-Scrolls-and-Skillbooks#4]
As the recipe stated: Cutting Tool + Feather = Quill, but the problem is, I can't figure out what's the "cutting tool" in the game? Dagger? Or specific item? In wiki they said cutting tool = dagger (which only available in Fort Joy, I'm in act 2 already). Please help.

**Comment by Shresht7** [comment]
Hi @bakaemon,
`CuttingTool` is a `ComboCategory` applied to several items like knives, daggers, swords, axes, shears etc.

![Screenshot-2022-01-06](https://user-images.githubusercontent.com/59516096/148360892-e1d76127-7755-44cb-ad27-806a2306aa13.png)

Any knife, sword, or sharp-weapon should satisfy the crafting-recipe.

**Comment by bakaemon** [comment]
Hi @Shresht7 , thank you for the answer. I was sure to do the combination but...
![image](https://user-images.githubusercontent.com/69375806/148367112-cf82df9a-13ea-4be2-944b-a2104dfa2b80.png)
It resulted invalid combination. The dagger itself is underleved epic tier. Does that count as cutting tool?
I also tried dwarven knife which is a common tier but also failed.
I was sure that the mod's on.
![image](https://user-images.githubusercontent.com/69375806/148367448-ff346349-9a93-47ce-b6ed-b0b0211dca5e.png)

**Comment by Shresht7** [comment]
The `CuttingTool + Feather = Quill` recipe is not actually a part of this mod. It's in the base-game ...
... or so I originally thought. As it turns out though, it belongs to the *crafter's kit* giftbag.

Thanks for bringing up the issue. I'll update the mod to create this recipe automatically for users that don't use the giftbags.

In the meantime, your options are:
1. Find or buy a quill. There should be some in Driftwood or the Lady Vengeance somewhere.
2. Enable the *crafter's kit* giftbag. It is one of the better giftbags.
3. Wait for the update. It shouldn't take long.

**Comment by bakaemon** [comment]
Dear @Shresht7 , thank you for your time and effort. I wish you best of luck!

**Comment by Shresht7** [comment]
I've pushed a hotfix, you should be able to use the quill crafting recipe now. Let me know if it works.

You are welcome. 🙂
